import type { TestCase } from './types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type TC = any[];

function tc(suite: string, data: TC[]): TestCase[] {
  return data.map(([id, title, type, priority, status, _suiteId, preconditions, assignee, tags, steps]: any) => ({
    id, title, type, priority, status, suiteId: suite,
    automationStatus: type === 'automated' ? 'automated' : 'manual',
    preconditions, tags,
    steps: steps.map(([action, expected]: [string, string], i: number) => ({ stepNumber: i + 1, action, expectedResult: expected })),
    history: status !== 'not_run' ? [
      { runId: 'run-001', date: '2026-05-15', status, tester: assignee, duration: `${(Math.random()*2+0.1).toFixed(1)}s` },
    ] : [],
    assignedTo: assignee, lastRunDate: status !== 'not_run' ? '2026-05-15' : null,
    linkedDefects: [], createdAt: '2026-04-01', updatedAt: '2026-05-15',
  }));
}

const uiRender: TC[] = [
  ['TC-UI-001','Dashboard shows portfolio SIS, quadrant distribution, priority actions','manual','high','pass','suite-ui-render','Application loaded with data','Sarah Wanjiku',['ui','dashboard','render'],[['Navigate to Dashboard','Dashboard renders all sections'],['Verify portfolio SIS metric is displayed','SIS number visible in health bar'],['Check quadrant distribution display','All 4 quadrants shown with counts']]],
  ['TC-UI-002','Dashboard activity feed shows colored dots per event type','manual','medium','pass','suite-ui-render','Dashboard loaded','James Ochieng',['ui','dashboard','activity'],[['View activity feed section','Feed shows recent entries'],['Verify colored dots by type','Different actions have different colored indicators']]],
  ['TC-UI-003','Stakeholders table shows portrait, name, org, SIS, quadrant for all 47','manual','high','pass','suite-ui-render','Application loaded','Sarah Wanjiku',['ui','stakeholders','table'],[['Navigate to Stakeholders page','Table loads'],['Verify columns present','Portrait, Name, Org, SIS, Quadrant columns visible'],['Count total rows','47 rows displayed']]],
  ['TC-UI-004','Stakeholders filter by quadrant reduces table to correct subset','manual','high','pass','suite-ui-render','Stakeholders page loaded','James Ochieng',['ui','stakeholders','filter'],[['Select "Strategic Ally" filter','Table shows only strategic ally stakeholders'],['Verify count matches expected','Correct number of filtered results']]],
  ['TC-UI-005','StakeholderDetail shows profile header, tabs, scoring breakdown','manual','high','pass','suite-ui-render','Stakeholder selected','Sarah Wanjiku',['ui','detail','profile'],[['Navigate to stakeholder detail','Profile page loads'],['Verify header with name, org, portrait','All profile header elements visible'],['Check tabs are present','Overview, Engagements, Scores tabs visible']]],
  ['TC-UI-006','StakeholderDetail engagements tab expands accordion on click','manual','high','pass','suite-ui-render','Stakeholder detail loaded','James Ochieng',['ui','detail','accordion'],[['Click Engagements tab','Engagements list loads'],['Click an engagement accordion row','Accordion expands showing details']]],
  ['TC-UI-007','QuadrantMap scatter plot has dots sized by SIS, colored by quadrant','manual','high','fail','suite-ui-render','Application loaded','Sarah Wanjiku',['ui','quadrant','visualization'],[['Navigate to Quadrant Map','Scatter plot renders'],['Verify dot sizes vary by SIS score','Higher SIS = larger dots'],['Verify dot colors match quadrant','4 distinct quadrant colors used']]],
  ['TC-UI-008','Engagements table row click opens EngagementDetailModal','manual','critical','pass','suite-ui-render','Engagements page loaded','James Ochieng',['ui','engagements','modal'],[['Click an engagement row','EngagementDetailModal opens'],['Verify modal shows full engagement details','All fields displayed']]],
  ['TC-UI-009','Engagements table row does NOT navigate to stakeholder profile','manual','critical','pass','suite-ui-render','Engagements page loaded','Sarah Wanjiku',['ui','engagements','navigation'],[['Click an engagement row','Modal opens, page does NOT change'],['Verify URL/page state unchanged','Still on Engagements page']]],
  ['TC-UI-010','Watchlist critical signals show pulsing left border animation','manual','medium','blocked','suite-ui-render','Watchlist loaded with critical signal','James Ochieng',['ui','watchlist','animation'],[['Navigate to Watchlist','Watchlist renders'],['Find a critical severity signal','Signal row has pulsing left border animation']]],
  ['TC-UI-011','Add Stakeholder live preview updates SIS and quadrant in real time','manual','high','pass','suite-ui-render','Add Stakeholder form open','Sarah Wanjiku',['ui','add-stakeholder','preview'],[['Open Add Stakeholder form','Form loads with live preview panel'],['Adjust scoring sliders','SIS value updates in real time'],['Verify quadrant classification updates','Quadrant label changes based on scores']]],
  ['TC-UI-012','Add Stakeholder requires portrait upload before submission','manual','high','not_run','suite-ui-render','Add Stakeholder form open','James Ochieng',['ui','add-stakeholder','validation'],[['Fill all form fields except portrait','Form is filled'],['Click submit without portrait','Validation error shown for portrait field'],['Upload portrait and submit','Form submits successfully']]],
  ['TC-UI-013','Users & Access shows edit button per row and add user button','manual','medium','pass','suite-ui-render','Users page loaded','Sarah Wanjiku',['ui','users','buttons'],[['Navigate to Users page','User list loads'],['Verify edit button on each row','Each user row has edit button'],['Verify Add User button is visible','Button present in header area']]],
  ['TC-UI-014','Scoring Config sliders adjust weight values but do not persist','manual','medium','not_run','suite-ui-render','Scoring Config page loaded','James Ochieng',['ui','scoring-config','sliders'],[['Navigate to Scoring Configuration','Config page loads with sliders'],['Adjust weight sliders','Values change in real time'],['Refresh page','Sliders reset to default values']]],
  ['TC-UI-015','DataStreams shows TV/radio/print/social tabs with filter chips','manual','medium','not_run','suite-ui-render','DataStreams page loaded','Sarah Wanjiku',['ui','datastreams','tabs'],[['Navigate to DataStreams','Page loads with tabs'],['Verify TV, Radio, Print, Social tabs','All 4 tabs visible'],['Click filter chips','Content filters correctly']]],
];

const uiFlow: TC[] = [
  ['TC-FLOW-001','Log Engagement modal creates engagement record visible in engagements list','manual','critical','pass','suite-ui-flow','Stakeholder detail loaded','James Ochieng',['workflow','engagement','create'],[['Click "Log Engagement" button','Modal opens with form'],['Fill engagement form fields','All fields populated'],['Click Submit','Modal closes, success notification shown'],['Navigate to Engagements list','New engagement visible in list']]],
  ['TC-FLOW-002','Score Update panel recalculates SIS in real time as scores change','manual','critical','pass','suite-ui-flow','Score Update panel open for a stakeholder','Sarah Wanjiku',['workflow','scoring','realtime'],[['Note initial SIS value','Initial value recorded'],['Adjust Influence score slider','SIS recalculates immediately'],['Adjust multiple component scores','SIS continues to update in real time']]],
  ['TC-FLOW-003','Score Update panel supports evidence file upload per component','manual','high','not_run','suite-ui-flow','Score Update panel open','James Ochieng',['workflow','scoring','evidence'],[['Click evidence upload button next to a component','File picker opens'],['Select a file','File name appears as attached evidence'],['Verify upload indicator shows for that component','Upload status shown']]],
  ['TC-FLOW-004','Add to Watchlist modal creates signal visible on Watchlist page','manual','high','pass','suite-ui-flow','Stakeholder detail loaded','Sarah Wanjiku',['workflow','watchlist','create'],[['Click "Add to Watchlist" button','Watchlist modal opens'],['Fill signal details','Form populated'],['Submit','Signal created, confirmation shown'],['Navigate to Watchlist page','New signal appears in list']]],
  ['TC-FLOW-005','Resolve Watchlist signal via confirm flow removes from active list','manual','high','pass','suite-ui-flow','Watchlist with active signal','James Ochieng',['workflow','watchlist','resolve'],[['Click resolve button on a signal','Confirmation dialog appears'],['Confirm resolution','Signal removed from active list'],['Check resolved signals tab','Signal appears in resolved list']]],
  ['TC-FLOW-006','Add Stakeholder form saves and new stakeholder appears in list','manual','critical','pass','suite-ui-flow','Application loaded','Sarah Wanjiku',['workflow','stakeholder','create'],[['Click "Add Stakeholder"','Form opens'],['Fill all required fields including portrait','Form completed'],['Click Save','Success notification, redirect to stakeholder list'],['Search for new stakeholder name','New stakeholder appears in results']]],
  ['TC-FLOW-007','Export CSV from Stakeholders page downloads file with correct columns','manual','high','not_run','suite-ui-flow','Stakeholders page loaded','James Ochieng',['workflow','export','csv'],[['Click Export CSV button','Browser downloads CSV file'],['Open CSV file','File contains correct column headers'],['Verify data rows match table','All 47 stakeholders present with correct data']]],
  ['TC-FLOW-008','Global search (Cmd+K) finds stakeholders by name and organization','manual','high','pass','suite-ui-flow','Application loaded','Sarah Wanjiku',['workflow','search','global'],[['Press Cmd+K','Search modal opens'],['Type stakeholder name','Results show matching stakeholders'],['Clear and type organization name','Results show stakeholders from that organization']]],
  ['TC-FLOW-009','Sidebar collapse/expand preserves active page','manual','medium','pass','suite-ui-flow','Application loaded on any page','James Ochieng',['workflow','sidebar','collapse'],[['Note current active page','Page recorded'],['Click sidebar collapse button','Sidebar collapses to icon-only mode'],['Verify page content unchanged','Same page still displayed'],['Click expand button','Sidebar expands, same page still active']]],
  ['TC-FLOW-010','User switching via dropdown changes current user context','manual','medium','not_run','suite-ui-flow','Application loaded','Sarah Wanjiku',['workflow','user','switch'],[['Click user dropdown in header','User list appears'],['Select different user','User context switches'],['Verify user name updates in header','New user name displayed']]],
  ['TC-FLOW-011','Edit User modal updates user details in Users table','manual','medium','not_run','suite-ui-flow','Users page loaded','James Ochieng',['workflow','user','edit'],[['Click edit button on a user row','Edit modal opens with current data'],['Modify user fields','Fields updated'],['Save changes','Modal closes, table reflects changes']]],
  ['TC-FLOW-012','Dashboard quadrant card click navigates to filtered stakeholders view','manual','high','pass','suite-ui-flow','Dashboard loaded','Sarah Wanjiku',['workflow','dashboard','navigation'],[['Click a quadrant card on dashboard','Navigates to Stakeholders page'],['Verify filter is pre-applied','Stakeholder list filtered by clicked quadrant']]],
  ['TC-FLOW-013','AI Insights panel responds to typed queries with portfolio data','manual','medium','not_run','suite-ui-flow','AI Insights panel open','James Ochieng',['workflow','ai','insights'],[['Open AI Insights panel','Panel opens with input'],['Type a question about portfolio','AI responds with relevant data'],['Verify response references actual stakeholder data','Response contains real portfolio metrics']]],
  ['TC-FLOW-014','Toast notifications appear and auto-dismiss after 4 seconds','manual','low','pass','suite-ui-flow','Application loaded','Sarah Wanjiku',['workflow','toast','notification'],[['Trigger an action that shows a toast','Toast notification appears'],['Wait 4 seconds','Toast automatically dismisses'],['Verify toast is gone from DOM','No toast elements remain']]],
];

const api: TC[] = [
  ['TC-API-001','GET /api/stakeholders returns 200 with array of stakeholder objects','automated','critical','pass','suite-api','API server running, database seeded','James Ochieng',['api','stakeholders','get'],[['Send GET request to /api/stakeholders','Response status is 200'],['Parse response body','Body is an array of stakeholder objects'],['Verify array length','Contains expected number of stakeholders']]],
  ['TC-API-002','GET /api/stakeholders/:id returns correct stakeholder by ID','automated','critical','pass','suite-api','API server running, stakeholder exists','Sarah Wanjiku',['api','stakeholders','get-by-id'],[['Send GET request to /api/stakeholders/stk-001','Response status is 200'],['Verify response body','Contains correct stakeholder with matching ID']]],
  ['TC-API-003','POST /api/stakeholders creates new stakeholder, returns 201','automated','critical','pass','suite-api','API server running','James Ochieng',['api','stakeholders','create'],[['Send POST request with valid stakeholder payload','Response status is 201'],['Verify response body contains new ID','ID is generated and returned'],['GET the new stakeholder','Stakeholder exists in database']]],
  ['TC-API-004','PUT /api/stakeholders/:id updates stakeholder fields','automated','high','pass','suite-api','API server running, stakeholder exists','Sarah Wanjiku',['api','stakeholders','update'],[['Send PUT request with updated fields','Response status is 200'],['GET the updated stakeholder','Fields reflect the update']]],
  ['TC-API-005','POST /api/scores creates new score snapshot with calculated SIS','automated','critical','fail','suite-api','API server running, stakeholder exists','James Ochieng',['api','scores','create'],[['Send POST request with score component values','Response status is 201'],['Verify response contains calculated SIS','SIS value is present and correct'],['Verify snapshot is linked to stakeholder','Stakeholder score history includes new snapshot']]],
  ['TC-API-006','GET /api/scores/:stakeholderId returns score history sorted by date desc','automated','high','pass','suite-api','API server running, multiple scores exist','Sarah Wanjiku',['api','scores','history'],[['Send GET request for stakeholder scores','Response status is 200'],['Verify sorting','First item has most recent date'],['Verify all items belong to correct stakeholder','All stakeholder IDs match']]],
  ['TC-API-007','POST /api/engagements creates engagement record','automated','high','pass','suite-api','API server running','James Ochieng',['api','engagements','create'],[['Send POST request with engagement payload','Response status is 201'],['Verify response body','Contains engagement with generated ID']]],
  ['TC-API-008','GET /api/watchlist returns active signals sorted by severity','automated','high','pass','suite-api','API server running, watchlist signals exist','Sarah Wanjiku',['api','watchlist','get'],[['Send GET request to /api/watchlist','Response status is 200'],['Verify sorting','Critical signals appear before lower severity']]],
  ['TC-API-009','PATCH /api/watchlist/:id/resolve marks signal as resolved','automated','high','pass','suite-api','API server running, active signal exists','James Ochieng',['api','watchlist','resolve'],[['Send PATCH request to resolve signal','Response status is 200'],['GET the signal','is_resolved is true, resolved_at is set']]],
  ['TC-API-010','POST /api/evidence uploads file and links to snapshot','automated','medium','not_run','suite-api','API server running, snapshot exists','Sarah Wanjiku',['api','evidence','upload'],[['Send POST with multipart file data','Response status is 201'],['Verify file is stored','File accessible at returned URL'],['Verify link to snapshot','Snapshot references the evidence file']]],
  ['TC-API-011','Authentication: unauthorized request returns 401','automated','critical','pass','suite-api','API server running','James Ochieng',['api','auth','unauthorized'],[['Send request without auth token','Response status is 401'],['Verify error message','Response contains "unauthorized" message']]],
  ['TC-API-012','Rate limiting: >100 requests/minute returns 429','automated','medium','not_run','suite-api','API server running','Sarah Wanjiku',['api','rate-limit','throttle'],[['Send 101 requests within 1 minute','First 100 return 200'],['Verify 101st request','Response status is 429 with retry-after header']]],
];

const integration: TC[] = [
  ['TC-INT-001','Score submission triggers watchlist signal if SIS drops >10 points','automated','critical','pass','suite-integration','Stakeholder with existing score, scoring engine active','Sarah Wanjiku',['integration','scoring','watchlist'],[['Submit score that reduces SIS by more than 10 points','Score is saved'],['Check watchlist','New signal auto-created for SIS drop'],['Verify signal severity','Severity matches the magnitude of the drop']]],
  ['TC-INT-002','New stakeholder appears in quadrant map at correct position','manual','high','pass','suite-integration','Stakeholder created with known scores','James Ochieng',['integration','stakeholder','quadrant'],[['Create a new stakeholder with specific scores','Stakeholder saved'],['Navigate to Quadrant Map','Map renders'],['Find new stakeholder dot','Dot positioned at correct Power/Convertibility coordinates']]],
  ['TC-INT-003','Engagement logged for stakeholder updates engagement count on profile','manual','high','pass','suite-integration','Stakeholder with known engagement count','Sarah Wanjiku',['integration','engagement','count'],[['Note current engagement count on profile','Count recorded'],['Log a new engagement for this stakeholder','Engagement saved'],['Return to profile','Engagement count incremented by 1']]],
  ['TC-INT-004','Score approval workflow transitions draft -> submitted -> approved','manual','critical','blocked','suite-integration','Score snapshot in draft status, approver role available','James Ochieng',['integration','scoring','approval'],[['Submit draft score for approval','Status changes to "submitted"'],['Login as approver role','Approver view loaded'],['Approve the score','Status changes to "approved"'],['Verify score is now active','Active score matches approved snapshot']]],
  ['TC-INT-005','PostgreSQL: stakeholder CRUD operations persist across page refresh','automated','critical','pass','suite-integration','PostgreSQL database running, stakeholder data seeded','Sarah Wanjiku',['integration','database','persistence'],[['Create a new stakeholder via API','201 response'],['Refresh the page','Page reloads'],['Query for the stakeholder','Stakeholder still exists in database']]],
  ['TC-INT-006','Redis: scoring weights cache invalidates on config change','automated','high','fail','suite-integration','Redis running, scoring weights cached','James Ochieng',['integration','cache','invalidation'],[['Read current cached weights','Weights retrieved from Redis'],['Update scoring configuration','Config saved'],['Read weights again','New weights returned, old cache invalidated']]],
  ['TC-INT-007','Kafka: data pipeline ingests external media source and creates DataStream item','automated','high','not_run','suite-integration','Kafka cluster running, consumer active','Sarah Wanjiku',['integration','kafka','pipeline'],[['Publish media record to Kafka topic','Record sent'],['Wait for consumer processing','Consumer acknowledges message'],['Check DataStream items','New item created from ingested media']]],
  ['TC-INT-008','ChromaDB: evidence text is vector-searchable after upload','automated','medium','not_run','suite-integration','ChromaDB running, evidence collection exists','James Ochieng',['integration','vector','search'],[['Upload text evidence for a stakeholder','Evidence stored'],['Perform semantic search with related query','Search returns the uploaded evidence'],['Verify relevance score','Score exceeds minimum threshold']]],
];

const perf: TC[] = [
  ['TC-PERF-001','Dashboard page loads in under 2 seconds (Lighthouse)','automated','high','pass','suite-perf','Application deployed to production','James Ochieng',['performance','lighthouse','load'],[['Run Lighthouse audit on Dashboard URL','Performance score recorded'],['Check First Contentful Paint','FCP under 1.5 seconds'],['Check Time to Interactive','TTI under 2.0 seconds']]],
  ['TC-PERF-002','Stakeholder list renders 500+ records without frame drops','automated','high','pass','suite-perf','Application loaded with 500+ test records','Sarah Wanjiku',['performance','rendering','virtualization'],[['Load stakeholder list with 500+ records','List renders'],['Scroll through entire list','No visible jank or frame drops'],['Measure FPS during scroll','FPS stays above 30']]],
  ['TC-PERF-003','Scoring engine calculates 1000 SIS scores in under 100ms','automated','medium','pass','suite-perf','Scoring engine module loaded','James Ochieng',['performance','scoring','benchmark'],[['Generate 1000 random score inputs','Inputs prepared'],['Run calculateSIS 1000 times','All calculations complete'],['Measure total elapsed time','Total under 100ms']]],
  ['TC-PERF-004','API: GET /api/stakeholders responds in under 200ms with 500 records','automated','high','not_run','suite-perf','API server running, 500 records in database','Sarah Wanjiku',['performance','api','response-time'],[['Send GET /api/stakeholders','Response received'],['Measure response time','Under 200ms'],['Verify all 500 records returned','Response contains 500 items']]],
  ['TC-PERF-005','Concurrent: 50 simultaneous score submissions complete without errors','automated','medium','not_run','suite-perf','API server running','James Ochieng',['performance','concurrency','stress'],[['Send 50 simultaneous POST /api/scores requests','All requests sent'],['Wait for all responses','All 50 complete'],['Verify no errors','All responses are 201, no 500 errors']]],
  ['TC-PERF-006','Memory: no memory leaks after 100 page navigations (heap stable)','automated','medium','not_run','suite-perf','Application loaded in Chrome DevTools','Sarah Wanjiku',['performance','memory','leak'],[['Record initial heap size','Baseline recorded'],['Navigate between pages 100 times','Navigations complete'],['Record final heap size','Heap growth is minimal (< 10% of baseline)']]],
];

const security: TC[] = [
  ['TC-SEC-001','XSS: script tags in stakeholder name input are sanitized','automated','critical','pass','suite-security','Application loaded','James Ochieng',['security','xss','sanitization'],[['Enter <script>alert("xss")</script> in name field','Input is accepted'],['Save and view stakeholder','Script tags are escaped, no alert fires'],['Inspect rendered HTML','Content is escaped, not executable']]],
  ['TC-SEC-002','SQL injection: malicious input in search does not execute','automated','critical','pass','suite-security','Application loaded','Sarah Wanjiku',['security','sql-injection','input'],[['Enter SQL injection payload in search: " OR 1=1 --','Search executes'],['Verify results','Only legitimate matches returned, no data leak'],['Check server logs','No SQL errors or unexpected queries']]],
  ['TC-SEC-003','CSRF: state-changing requests require valid token','automated','high','pass','suite-security','API server running','James Ochieng',['security','csrf','token'],[['Send POST request without CSRF token','Response is 403'],['Send POST request with valid CSRF token','Response is 201/200']]],
  ['TC-SEC-004','Auth: expired JWT returns 401, not stale data','automated','high','pass','suite-security','API server running, expired JWT available','Sarah Wanjiku',['security','jwt','expiry'],[['Send request with expired JWT','Response status is 401'],['Verify no data in response body','Body contains error message only']]],
  ['TC-SEC-005','RBAC: viewer role cannot access score update panel','manual','high','not_run','suite-security','Application loaded with viewer role user','James Ochieng',['security','rbac','viewer'],[['Login as viewer role','Dashboard loads'],['Navigate to stakeholder detail','Profile visible'],['Attempt to open Score Update panel','Panel does not open or button is hidden']]],
  ['TC-SEC-006','RBAC: only approver role can approve score snapshots','manual','high','not_run','suite-security','Application loaded, pending score exists','Sarah Wanjiku',['security','rbac','approver'],[['Login as tester role','Dashboard loads'],['Navigate to pending score','Score visible but approve button is disabled'],['Login as approver role','Approve button is enabled'],['Approve the score','Status changes to approved']]],
  ['TC-SEC-007','Sensitive stakeholders are not exposed in API responses for viewer role','automated','critical','pass','suite-security','API running, sensitive stakeholders flagged','James Ochieng',['security','rbac','data-exposure'],[['Authenticate as viewer role','Token received'],['GET /api/stakeholders','Response received'],['Check for sensitive stakeholders','Sensitive records are excluded from response']]],
  ['TC-SEC-008','File upload validates file type and size before processing','manual','medium','not_run','suite-security','Application loaded, file upload available','Sarah Wanjiku',['security','upload','validation'],[['Attempt to upload .exe file','Rejected with file type error'],['Attempt to upload 50MB image','Rejected with file size error'],['Upload valid 2MB PNG','Upload succeeds']]],
];

const pipeline: TC[] = [
  ['TC-PIPE-001','Airflow DAG runs on schedule and completes without failure','automated','high','pass','suite-pipeline','Airflow scheduler running, DAG registered','James Ochieng',['pipeline','airflow','dag'],[['Trigger DAG run','DAG starts executing'],['Wait for completion','DAG completes all tasks'],['Check task statuses','All tasks show "success" status']]],
  ['TC-PIPE-002','Kafka consumer processes ingested media records and writes to PostgreSQL','automated','high','pass','suite-pipeline','Kafka cluster running, consumer active, PostgreSQL connected','Sarah Wanjiku',['pipeline','kafka','consumer'],[['Publish 10 media records to Kafka topic','Records sent'],['Wait for consumer processing','Consumer lag reaches 0'],['Query PostgreSQL','10 new records present in media table']]],
  ['TC-PIPE-003','Spark job transforms raw scraper data into structured stakeholder updates','automated','medium','not_run','suite-pipeline','Spark cluster running, raw data available','James Ochieng',['pipeline','spark','transform'],[['Submit Spark job with raw scraper data','Job starts'],['Wait for completion','Job completes successfully'],['Check output dataset','Structured stakeholder updates generated']]],
  ['TC-PIPE-004','Pipeline handles malformed input gracefully without crashing','automated','high','pass','suite-pipeline','Pipeline running','Sarah Wanjiku',['pipeline','error-handling','resilience'],[['Submit malformed JSON to Kafka topic','Record ingested'],['Check consumer status','Consumer is still running (not crashed)'],['Check dead letter queue','Malformed record routed to DLQ']]],
  ['TC-PIPE-005','End-to-end: RapidAPI social scrape -> Kafka -> Spark -> PostgreSQL -> UI','manual','critical','blocked','suite-pipeline','Full pipeline stack running','James Ochieng',['pipeline','e2e','full-stack'],[['Trigger RapidAPI social media scrape','Scrape completes'],['Verify Kafka receives scraped data','Messages in topic'],['Verify Spark processes data','Transformation complete'],['Check PostgreSQL for new records','Records persisted'],['Verify data visible in UI DataStreams page','New data items shown']]],
];

const compat: TC[] = [
  ['TC-COMPAT-001','MSIT renders correctly on Chrome 120+','manual','high','pass','suite-compat','MSIT deployed, Chrome 120+ available','Sarah Wanjiku',['compat','chrome','rendering'],[['Open MSIT in Chrome 120+','Application loads'],['Navigate all pages','All pages render correctly'],['Test core interactions','All interactions functional']]],
  ['TC-COMPAT-002','MSIT renders correctly on Firefox 120+','manual','medium','pass','suite-compat','MSIT deployed, Firefox 120+ available','James Ochieng',['compat','firefox','rendering'],[['Open MSIT in Firefox 120+','Application loads'],['Navigate all pages','All pages render correctly'],['Test core interactions','All interactions functional']]],
  ['TC-COMPAT-003','MSIT renders correctly on Safari 17+','manual','medium','not_run','suite-compat','MSIT deployed, Safari 17+ available','Sarah Wanjiku',['compat','safari','rendering'],[['Open MSIT in Safari 17+','Application loads'],['Navigate all pages','All pages render correctly'],['Test core interactions','All interactions functional']]],
  ['TC-COMPAT-004','MSIT renders correctly on Edge 120+','manual','medium','pass','suite-compat','MSIT deployed, Edge 120+ available','James Ochieng',['compat','edge','rendering'],[['Open MSIT in Edge 120+','Application loads'],['Navigate all pages','All pages render correctly']]],
  ['TC-COMPAT-005','MSIT layout is usable at 1024px width','manual','high','pass','suite-compat','MSIT deployed','Sarah Wanjiku',['compat','responsive','1024'],[['Resize browser to 1024px width','Layout adjusts'],['Verify sidebar behavior','Sidebar collapses or adjusts'],['Verify content is not cut off','All content accessible']]],
  ['TC-COMPAT-006','MSIT layout is usable at 1440px and 1920px widths','manual','medium','pass','suite-compat','MSIT deployed','James Ochieng',['compat','responsive','wide'],[['Resize browser to 1440px','Layout uses available space'],['Resize browser to 1920px','Layout scales appropriately'],['Verify no excessive whitespace','Content well-distributed']]],
];

export const uiRenderTests = tc('suite-ui-render', uiRender);
export const uiFlowTests = tc('suite-ui-flow', uiFlow);
export const apiTests = tc('suite-api', api);
export const integrationTests = tc('suite-integration', integration);
export const perfTests = tc('suite-perf', perf);
export const securityTests = tc('suite-security', security);
export const pipelineTests = tc('suite-pipeline', pipeline);
export const compatTests = tc('suite-compat', compat);
