import type { TestCase } from './types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type TC = any[];

function tc(suite: string, data: TC[]): TestCase[] {
  return data.map(([id, title, type, priority, status, _suiteId, preconditions, assignee, tags, steps]: any) => ({
    id, title, type, priority, status, suiteId: suite,
    automationStatus: type === 'automated' ? 'automated' : 'manual',
    preconditions, tags,
    steps: steps.map(([action, expected]: [string, string], i: number) => ({ stepNumber: i + 1, action, expectedResult: expected })),
    history: status !== 'not_run' ? [
      { runId: 'run-001', date: '2026-05-15', status, tester: assignee, duration: `${(Math.random() * 2 + 0.1).toFixed(1)}s` },
      { runId: 'run-002', date: '2026-05-10', status: 'pass', tester: assignee, duration: `${(Math.random() * 2 + 0.1).toFixed(1)}s` },
    ] : [],
    assignedTo: assignee, lastRunDate: status !== 'not_run' ? '2026-05-15' : null,
    linkedDefects: [], createdAt: '2026-04-01', updatedAt: '2026-05-15',
  }));
}

const smoke: TC[] = [
  ['TC-SMOKE-001','Application loads without console errors','manual','critical','pass','suite-smoke','Application deployed and accessible','Ultron QA',['smoke','load','health'],[['Navigate to application root URL','Page loads completely with no console errors'],['Open browser developer tools console','Console shows zero errors or warnings'],['Verify main layout renders (sidebar, header, content area)','All layout sections are visible and properly styled']]],
  ['TC-SMOKE-002','Dashboard page renders with campaign data','manual','critical','pass','suite-smoke','Application loaded, user authenticated','Ultron QA',['smoke','dashboard','render'],[['Navigate to Dashboard page','Dashboard loads with all three row sections'],['Verify health bar shows total test cases and pass rate','Health bar displays correct numbers'],['Check that trend charts render without errors','Both charts display with data points']]],
  ['TC-SMOKE-003','Sidebar navigation visits all 11 pages without crash','manual','critical','pass','suite-smoke','Application loaded','Ultron QA',['smoke','navigation','sidebar'],[['Click each of the 11 sidebar navigation items sequentially','Each page loads without errors'],['Verify page title changes for each navigation','Header shows correct page title'],['Check browser console after visiting all pages','No JavaScript errors logged']]],
  ['TC-SMOKE-004','Global search (Cmd+K) opens and finds stakeholders','manual','high','pass','suite-smoke','Application loaded with stakeholder data','Ultron QA',['smoke','search','cmd-k'],[['Press Cmd+K (or Ctrl+K on Windows)','Search modal opens with focused input'],['Type a stakeholder name','Results list shows matching stakeholders'],['Press Escape','Search modal closes']]],
  ['TC-SMOKE-005','Stakeholder list loads 47 records with portraits','manual','high','pass','suite-smoke','Application loaded, stakeholder data seeded','Ultron QA',['smoke','stakeholders','list'],[['Navigate to Stakeholders page','Page loads with table view'],['Count total rows in stakeholder table','Table shows exactly 47 records'],['Verify each row has a portrait image','All rows display portrait thumbnails']]],
  ['TC-SMOKE-006','Quadrant map scatter plot renders all dots','manual','high','fail','suite-smoke','Application loaded, stakeholder data seeded','Ultron QA',['smoke','quadrant','scatter'],[['Navigate to Quadrant Map page','Scatter plot renders with axes'],['Count dots on the scatter plot','All 47 stakeholder dots are visible'],['Verify dots are colored by quadrant classification','Each quadrant uses distinct color']]],
  ['TC-SMOKE-007','Score update panel opens and shows 6 components','manual','high','pass','suite-smoke','Application loaded, stakeholder selected','Ultron QA',['smoke','scoring','panel'],[['Navigate to any stakeholder detail page','Stakeholder profile loads'],['Click "Update Score" button','Score update panel slides open'],['Verify 6 scoring components are visible','Influence, Relationship, Risk, Sentiment, Alignment, Impact all shown']]],
  ['TC-SMOKE-008','Add Stakeholder form loads with all 5 sections','manual','high','pass','suite-smoke','Application loaded','Ultron QA',['smoke','add-stakeholder','form'],[['Click "Add Stakeholder" button','Form modal or page opens'],['Verify all 5 form sections are present','Personal Info, Organization, Scoring, Classification, Portrait sections visible'],['Check that all required field indicators are shown','Required fields marked with visual indicator']]],
];

const unit: TC[] = [
  ['TC-UNIT-001','invertRisk(1) returns 5','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','sis','risk','unit'],[['Call invertRisk(1)','Returns 5']]],
  ['TC-UNIT-002','invertRisk(5) returns 1','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','sis','risk','unit'],[['Call invertRisk(5)','Returns 1']]],
  ['TC-UNIT-003','invertRisk(3) returns 3','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','sis','risk','unit'],[['Call invertRisk(3)','Returns 3']]],
  ['TC-UNIT-004','calculateSIS with all-max scores returns 100.00','automated','critical','pass','suite-unit','Scoring engine module loaded, default weights applied','Ultron QA',['scoring','sis','calculation','regression'],[['Call calculateSIS({ influence: 5, relationship: 5, risk: 1, sentiment: 5, alignment: 5, impact: 5 })','Returns 100.00']]],
  ['TC-UNIT-005','calculateSIS with all-min scores returns 20.00','automated','critical','pass','suite-unit','Scoring engine module loaded, default weights applied','Ultron QA',['scoring','sis','calculation','regression'],[['Call calculateSIS({ influence: 1, relationship: 1, risk: 5, sentiment: 1, alignment: 1, impact: 1 })','Returns 20.00']]],
  ['TC-UNIT-006','calculateSIS for Hon. Mwangi (I:5,R:3,K:3,S:3,A:2,M:5) returns 74.00','automated','critical','pass','suite-unit','Scoring engine module loaded, default weights applied','Ultron QA',['scoring','sis','calculation','regression'],[['Call calculateSIS({ influence: 5, relationship: 3, risk: 3, sentiment: 3, alignment: 2, impact: 5 })','Returns 74.00']]],
  ['TC-UNIT-007','calculateSIS for Dr. Ultron QA (I:5,R:4,K:1,S:5,A:5,M:4) returns 92.00','automated','critical','pass','suite-unit','Scoring engine module loaded, default weights applied','Ultron QA',['scoring','sis','calculation','regression'],[['Call calculateSIS({ influence: 5, relationship: 4, risk: 1, sentiment: 5, alignment: 5, impact: 4 })','Returns 92.00']]],
  ['TC-UNIT-008','calculatePowerAxis(5, 5) returns 5.000','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','power-axis','unit'],[['Call calculatePowerAxis(5, 5)','Returns 5.000']]],
  ['TC-UNIT-009','calculatePowerAxis(1, 1) returns 1.000','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','power-axis','unit'],[['Call calculatePowerAxis(1, 1)','Returns 1.000']]],
  ['TC-UNIT-010','calculatePowerAxis(5, 3) returns 4.500','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','power-axis','unit'],[['Call calculatePowerAxis(5, 3)','Returns 4.500']]],
  ['TC-UNIT-011','calculateConvertibilityAxis(5, 5, 5) returns 4.995','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','convertibility','unit'],[['Call calculateConvertibilityAxis(5, 5, 5)','Returns 4.995']]],
  ['TC-UNIT-012','calculateConvertibilityAxis(1, 1, 1) returns 0.999','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','convertibility','unit'],[['Call calculateConvertibilityAxis(1, 1, 1)','Returns 0.999']]],
  ['TC-UNIT-013','classifyQuadrant(4.5, 4.5) returns strategic_ally','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','quadrant','classification'],[['Call classifyQuadrant(4.5, 4.5)','Returns "strategic_ally"']]],
  ['TC-UNIT-014','classifyQuadrant(4.5, 2.0) returns power_gap','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','quadrant','classification'],[['Call classifyQuadrant(4.5, 2.0)','Returns "power_gap"']]],
  ['TC-UNIT-015','classifyQuadrant(2.0, 4.5) returns hidden_champion','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','quadrant','classification'],[['Call classifyQuadrant(2.0, 4.5)','Returns "hidden_champion"']]],
  ['TC-UNIT-016','classifyQuadrant(2.0, 2.0) returns monitor_exit','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','quadrant','classification'],[['Call classifyQuadrant(2.0, 2.0)','Returns "monitor_exit"']]],
  ['TC-UNIT-017','classifyQuadrant at exact threshold (4.0, 4.0) returns strategic_ally','automated','critical','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','quadrant','boundary'],[['Call classifyQuadrant(4.0, 4.0)','Returns "strategic_ally"']]],
  ['TC-UNIT-018','classifyQuadrant just below threshold (3.99, 4.0) returns hidden_champion','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','quadrant','boundary'],[['Call classifyQuadrant(3.99, 4.0)','Returns "hidden_champion"']]],
  ['TC-UNIT-019','calculateFullScore returns correct ScoringResult object shape','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','full-score','shape'],[['Call calculateFullScore with valid inputs','Returns object with sis, powerAxis, convertibilityAxis, quadrant, tier, redFlags properties'],['Verify all numeric fields are numbers','All values are finite numbers'],['Verify quadrant is a valid quadrant string','Quadrant is one of the 4 valid values']]],
  ['TC-UNIT-020','detectRedFlags returns layer_influence_mismatch for Layer 1 with I<3','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','red-flags','detection'],[['Call detectRedFlags with Layer 1 stakeholder and influence score < 3','Returns array containing "layer_influence_mismatch" flag']]],
  ['TC-UNIT-021','detectRedFlags returns stale_assessment for >90 day old score','automated','high','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','red-flags','staleness'],[['Call detectRedFlags with last assessment date > 90 days ago','Returns array containing "stale_assessment" flag']]],
  ['TC-UNIT-022','getSISTier returns correct tier for boundary values (80, 60, 59)','automated','medium','pass','suite-unit','Scoring engine module loaded','Ultron QA',['scoring','sis','tier'],[['Call getSISTier(80)','Returns "High"'],['Call getSISTier(60)','Returns "Medium"'],['Call getSISTier(59)','Returns "Low"']]],
];

const store: TC[] = [
  ['TC-STORE-001','setPage changes currentPage and clears selectedStakeholderId','automated','high','pass','suite-store','Zustand store initialized','Ultron QA',['store','navigation','state'],[['Call setPage("dashboard")','currentPage is "dashboard" and selectedStakeholderId is null']]],
  ['TC-STORE-002','setSelectedStakeholder sets ID and forces page to stakeholder-detail','automated','high','pass','suite-store','Zustand store initialized','Ultron QA',['store','navigation','stakeholder'],[['Call setSelectedStakeholder("stk-001")','selectedStakeholderId is "stk-001" and currentPage is "stakeholder-detail"']]],
  ['TC-STORE-003','addSnapshot appends to snapshots array without mutating existing','automated','critical','pass','suite-store','Store initialized with existing snapshots','Ultron QA',['store','snapshots','immutability'],[['Record initial snapshots array reference','Store reference saved'],['Call addSnapshot with new snapshot object','New snapshot appears in array'],['Compare old reference with new','Original array reference is unchanged (immutable update)']]],
  ['TC-STORE-004','addEngagement appends to engagements array','automated','high','pass','suite-store','Store initialized','Ultron QA',['store','engagements','crud'],[['Call addEngagement with valid engagement object','Engagements array length increases by 1'],['Verify new engagement is at end of array','Last element matches input']]],
  ['TC-STORE-005','resolveWatchlistSignal sets is_resolved=true and sets resolved_at','automated','high','pass','suite-store','Store initialized with active watchlist signal','Ultron QA',['store','watchlist','resolve'],[['Call resolveWatchlistSignal with signal ID','Signal is_resolved is true and resolved_at is set to current timestamp']]],
  ['TC-STORE-006','addStakeholder appends to storeStakeholders','automated','high','pass','suite-store','Store initialized','Ultron QA',['store','stakeholders','crud'],[['Call addStakeholder with valid stakeholder object','storeStakeholders array length increases by 1']]],
  ['TC-STORE-007','addUser appends to storeUsers','automated','medium','pass','suite-store','Store initialized','Ultron QA',['store','users','crud'],[['Call addUser with valid user object','storeUsers array length increases by 1']]],
  ['TC-STORE-008','updateUser modifies correct user fields without affecting others','automated','medium','pass','suite-store','Store initialized with multiple users','Ultron QA',['store','users','update'],[['Call updateUser with partial user update','Target user fields are updated'],['Verify other users in array are unchanged','Non-target users retain original values']]],
  ['TC-STORE-009','addToast creates toast and auto-removes after 4 seconds','automated','medium','pass','suite-store','Store initialized','Ultron QA',['store','toast','auto-dismiss'],[['Call addToast with message','Toast appears in toasts array'],['Wait 4 seconds','Toast is automatically removed from array']]],
  ['TC-STORE-010','setFilter updates correct filter key without resetting others','automated','high','pass','suite-store','Store initialized with some filters set','Ultron QA',['store','filters','partial-update'],[['Set filter A to value X','Filter A is X'],['Set filter B to value Y','Filter A is still X, filter B is Y']]],
  ['TC-STORE-011','clearFilters resets all filters to defaults','automated','medium','pass','suite-store','Store initialized with multiple filters set','Ultron QA',['store','filters','reset'],[['Set multiple filters to non-default values','Filters are set'],['Call clearFilters','All filters return to default values']]],
  ['TC-STORE-012','openScoreUpdate sets stakeholderId and opens panel','automated','medium','pass','suite-store','Store initialized','Ultron QA',['store','score-update','panel'],[['Call openScoreUpdate("stk-001")','scoreUpdateStakeholderId is "stk-001" and isScoreUpdateOpen is true']]],
  ['TC-STORE-013','closeScoreUpdate clears stakeholderId and closes panel','automated','medium','pass','suite-store','Score update panel is open','Ultron QA',['store','score-update','panel'],[['Call closeScoreUpdate','scoreUpdateStakeholderId is null and isScoreUpdateOpen is false']]],
  ['TC-STORE-014','useStakeholdersWithScores returns 47 items with latest snapshots','automated','critical','pass','suite-store','Store initialized with full stakeholder + snapshot data','Ultron QA',['store','selectors','computed'],[['Call useStakeholdersWithScores selector','Returns array of exactly 47 items'],['Verify each item has latest snapshot attached','All items have score data with SIS values']]],
  ['TC-STORE-015','useFilteredStakeholders applies quadrant filter correctly','automated','high','pass','suite-store','Store initialized with stakeholder data','Ultron QA',['store','selectors','filter'],[['Set quadrant filter to "strategic_ally"','Filtered list contains only strategic_ally stakeholders']]],
  ['TC-STORE-016','useFilteredStakeholders applies search filter on name, org, title','automated','high','pass','suite-store','Store initialized with stakeholder data','Ultron QA',['store','selectors','search'],[['Set search filter to a known stakeholder name','Filtered list contains matching stakeholder'],['Set search filter to a known organization','Filtered list contains stakeholders from that org']]],
  ['TC-STORE-017','useFilteredStakeholders sort by sis_desc puts highest SIS first','automated','high','pass','suite-store','Store initialized with stakeholder data','Ultron QA',['store','selectors','sort'],[['Set sort to "sis_desc"','First item in filtered list has highest SIS score'],['Verify descending order','Each subsequent item has equal or lower SIS']]],
  ['TC-STORE-018','Modal open/close actions toggle state correctly for all 4 modals','automated','medium','pass','suite-store','Store initialized','Ultron QA',['store','modals','toggle'],[['Open each of 4 modals sequentially','Each modal state becomes true'],['Close each modal','Each modal state returns to false']]],
];

export const smokeTests = tc('suite-smoke', smoke);
export const unitTests = tc('suite-unit', unit);
export const storeTests = tc('suite-store', store);
